# Dynatrace Managed Environments Configuration

- dynatraceUrl: https://dynatrace.development.tech.ec.europa.eu
  apiEndpointUrl: https://intragate.development.ec.europa.eu/apmgw
  environmentId: 87889eb4-bb35-41ec-a521-adf5abcc6256
  alias: digit-dev
  # Environment variable interpolation - tokens are injected at runtime
  apiToken: ${DT_TOKEN}
